"""Deterministic symptom-to-condition matcher for the staff symptom assessment.

The PHP backend sends the symptoms a student described (free text entered by a
doctor or nurse). This module scores those symptoms against a curated knowledge
base of common university-health-centre conditions and returns the most likely
matches ranked by score.

This is a decision-support assistant, NOT a medical diagnosis. It never sees
PII (names, reg numbers, emails) and stores nothing.

Design notes:
  * Each condition defines a list of keyword *patterns* (single words or short
    phrases). A pattern matches if it appears in the normalized text with word
    boundaries on both sides, so "fever" does not match inside "feverfew".
  * score = fraction of the condition's own patterns that matched (coverage).
  * level is derived from score thresholds; confidence is a bounded estimate.
  * An empty / unrecognized symptom set returns no conditions and a safe
    advisory — it never guesses.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

MODEL_VERSION = "symptom-matcher-1.0"

RISK_LEVELS = ("low", "moderate", "high")
LEVEL_HIGH = 0.55
LEVEL_MODERATE = 0.30

MAX_TEXT_LEN = 2000
MAX_CONDITIONS = 6

DISCLAIMER = (
    "This suggestion is generated by a decision-support assistant from the "
    "symptoms entered by healthcare staff. It is informational only and is not "
    "a medical diagnosis. A qualified healthcare professional must confirm any "
    "condition and decide on treatment."
)


@dataclass(frozen=True)
class Condition:
    """One entry in the curated symptom knowledge base."""

    name: str
    patterns: tuple[str, ...]
    advice: str


@dataclass(frozen=True)
class SymptomResult:
    condition: str
    level: str
    score: float
    confidence: float
    advice: str


KNOWLEDGE_BASE: tuple[Condition, ...] = (
    Condition(
        name="Malaria",
        patterns=(
            "fever", "chills", "sweating", "shivering", "headache",
            "body aches", "muscle aches", "joint pain", "fatigue",
            "nausea", "vomiting", "high temperature",
        ),
        advice="Malaria is common in the region. A blood smear or rapid test "
               "is needed to confirm; treat under clinical supervision and "
               "complete the full course.",
    ),
    Condition(
        name="Typhoid fever",
        patterns=(
            "prolonged fever", "high fever", "headache", "abdominal pain",
            "weakness", "constipation", "diarrhea", "loss of appetite",
            "rose spots", "bradycardia", "stomach pain", "dry cough",
        ),
        advice="Prolonged fever plus abdominal symptoms warrants a Widal or "
               "blood culture before treatment. Consider referral for lab "
               "confirmation.",
    ),
    Condition(
        name="Influenza",
        patterns=(
            "fever", "cough", "sore throat", "runny nose", "muscle aches",
            "fatigue", "chills", "headache", "body aches", "congestion",
        ),
        advice="Supportive care (rest, fluids, antipyretics) and symptom "
               "monitoring. Antivirals are most useful within 48 hours of onset.",
    ),
    Condition(
        name="Common cold",
        patterns=(
            "runny nose", "sneezing", "sore throat", "cough", "nasal congestion",
            "stuffy nose", "mild headache", "scratchy throat",
        ),
        advice="Self-limiting. Rest, fluids and symptomatic relief usually "
               "suffice; monitor for worsening or prolonged symptoms.",
    ),
    Condition(
        name="Gastroenteritis",
        patterns=(
            "diarrhea", "vomiting", "nausea", "abdominal cramps", "stomach cramps",
            "stomach pain", "loose stools", "dehydration", "watery stool",
            "food poisoning",
        ),
        advice="Prevent dehydration with oral rehydration. Advise hand hygiene; "
               "refer for IV fluids if unable to keep fluids down.",
    ),
    Condition(
        name="Urinary tract infection",
        patterns=(
            "burning urination", "painful urination", "frequent urination",
            "urgency", "lower abdominal pain", "cloudy urine", "foul smelling urine",
            "blood in urine", "dysuria",
        ),
        advice="Urinalysis and culture-guided antibiotics are needed. Increase "
               "fluid intake and review predisposing factors.",
    ),
    Condition(
        name="Asthma exacerbation",
        patterns=(
            "wheezing", "shortness of breath", "difficulty breathing", "chest tightness",
            "breathlessness", "rapid breathing", "cough at night", "noisy breathing",
        ),
        advice="Assess severity immediately. Mild episodes respond to inhaled "
               "bronchodilators; refer urgently if speech is limited or oxygen "
               "saturation is low.",
    ),
    Condition(
        name="Migraine",
        patterns=(
            "severe headache", "throbbing headache", "one sided headache",
            "nausea", "vomiting", "sensitivity to light", "sensitivity to sound",
            "visual aura", "pulsating headache",
        ),
        advice="Identify and avoid triggers; simple analgesics early in an "
               "attack help. Escalate if neurological symptoms are new or "
               "worsening.",
    ),
    Condition(
        name="Tension headache",
        patterns=(
            "headache", "pressure around head", "tight band headache",
            "neck pain", "tension in neck", "mild headache", "scalp tenderness",
        ),
        advice="Usually stress-related; rest, hydration and simple analgesia "
               "are first-line. Worsening headache needs review.",
    ),
    Condition(
        name="Anaemia",
        patterns=(
            "fatigue", "weakness", "pale skin", "dizziness", "shortness of breath",
            "cold hands", "rapid heartbeat", "paleness", "easy tiredness",
        ),
        advice="A full blood count will confirm. Look for dietary, menstrual or "
               "parasitic causes and treat the underlying driver.",
    ),
    Condition(
        name="Hypertension",
        patterns=(
            "headache", "dizziness", "blurred vision", "nosebleeds", "chest pain",
            "palpitations", "high blood pressure", "flushing",
        ),
        advice="Measure blood pressure properly. High readings need repeat "
               "confirmation and lifestyle review; refer if very high or "
               "symptomatic.",
    ),
    Condition(
        name="Tonsillitis",
        patterns=(
            "sore throat", "difficulty swallowing", "swollen tonsils", "fever",
            "enlarged neck glands", "white spots on tonsils", "painful swallowing",
        ),
        advice="Rapid antigen or culture can distinguish viral from bacterial. "
               "Symptomatic care, and antibiotics only if bacterial.",
    ),
    Condition(
        name="Conjunctivitis",
        patterns=(
            "red eye", "itchy eye", "watery discharge", "gritty eye",
            "swollen eyelids", "sticky eye", "eye discharge", "pink eye",
        ),
        advice="Usually viral or allergic. Emphasize hand hygiene and avoid "
               "sharing towels; bacterial cases may need antibiotic drops.",
    ),
    Condition(
        name="Skin infection",
        patterns=(
            "itchy skin", "rash", "red rings", "skin lesions", "scaly patches",
            "ringworm", "itchy rash", "blisters on skin", "red itchy patches",
        ),
        advice="Identify the pattern (fungal, bacterial or parasitic). Topical "
               "or systemic treatment depends on the cause; keep skin clean and "
               "dry.",
    ),
    Condition(
        name="Dengue fever",
        patterns=(
            "high fever", "severe headache", "pain behind eyes", "joint pain",
            "muscle pain", "rash", "nausea", "vomiting", "bleeding gums",
            "easy bruising",
        ),
        advice="Supportive care with strict fluid balance and monitoring of "
               "platelets/haematocrit. Refer promptly if warning signs (bleeding, "
               "abdominal pain, lethargy) appear.",
    ),
)

_compiled: dict[str, re.Pattern[str]] = {}


def _pattern_regex(pattern: str) -> re.Pattern[str]:
    if pattern not in _compiled:
        _compiled[pattern] = re.compile(
            r"(?<!\w)" + re.escape(pattern.lower()) + r"(?!\w)",
            re.IGNORECASE,
        )
    return _compiled[pattern]


def _normalize(text: str) -> str:
    """Lowercase and collapse whitespace; enforce a safe length."""
    text = " ".join(text.split())
    return text[:MAX_TEXT_LEN].lower()


def _match_conditions(text: str) -> tuple[list[SymptomResult], list[str]]:
    """Score the normalized text against the knowledge base.

    Returns (ranked results, deduplicated matched patterns).
    """
    norm = _normalize(text)
    if not norm:
        return [], []

    matched_symptoms: list[str] = []
    results: list[SymptomResult] = []

    for condition in KNOWLEDGE_BASE:
        hit_patterns: list[str] = []
        for pattern in condition.patterns:
            if _pattern_regex(pattern).search(norm):
                hit_patterns.append(pattern)
                if pattern not in matched_symptoms:
                    matched_symptoms.append(pattern)

        if not hit_patterns:
            continue

        score = round(len(hit_patterns) / len(condition.patterns), 4)
        if score >= LEVEL_HIGH:
            level = "high"
        elif score >= LEVEL_MODERATE:
            level = "moderate"
        else:
            level = "low"

        # Confidence blends how much of the condition profile matched with a
        # floor so a single clear symptom is not reported as 0 confidence.
        confidence = round(min(0.9, 0.10 + score * 0.80), 4)

        results.append(
            SymptomResult(
                condition=condition.name,
                level=level,
                score=score,
                confidence=confidence,
                advice=condition.advice,
            )
        )

    results.sort(key=lambda r: (r.score, r.confidence), reverse=True)
    return results[:MAX_CONDITIONS], matched_symptoms


def assess(text: str) -> dict:
    """Public entry point: returns the validated decision-support payload."""
    results, matched = _match_conditions(text)
    return {
        "conditions": [
            {
                "condition": r.condition,
                "level": r.level,
                "score": r.score,
                "confidence": r.confidence,
                "advice": r.advice,
            }
            for r in results
        ],
        "matched_symptoms": matched,
        "model_version": MODEL_VERSION,
        "disclaimer": DISCLAIMER,
    }
