"""Pydantic request/response models.

Validation is strict so malformed input is rejected before any model code runs.
Privacy: the service only ever receives de-identified feature vectors prepared
by the PHP backend. PII (names, reg numbers, emails) must never be sent here.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Annotated, Literal

from pydantic import BaseModel, Field, field_validator

PredictionType = Literal[
    "malaria_risk",
    "asthma_exacerbation",
    "typhoid_risk",
]

MAX_FEATURES = 200
MAX_FEATURE_NAME_LEN = 80
MAX_STUDENT_REF_LEN = 128
MAX_SYMPTOM_TEXT_LEN = 2000


class PredictionRequest(BaseModel):
    """Input for a decision-support prediction.

    ``student_ref`` is an opaque identifier chosen by PHP (for example the
    student's internal user id). It is NOT shown in any UI and must never be
    PII. ``features`` must be numeric only.
    """

    prediction_type: Annotated[str, Field(min_length=1, max_length=80)]
    student_ref: Annotated[str, Field(max_length=MAX_STUDENT_REF_LEN)] = ""
    features: Annotated[dict[str, float], Field(max_length=MAX_FEATURES)]

    @field_validator("features")
    @classmethod
    def validate_features(cls, v: dict[str, float]) -> dict[str, float]:
        if not v:
            raise ValueError("features must not be empty")
        for name, value in v.items():
            if len(name) > MAX_FEATURE_NAME_LEN:
                raise ValueError(f"feature name too long: {name[:20]}...")
            if value != value:  # NaN
                raise ValueError(f"feature '{name}' is NaN")
            if value in (float("inf"), float("-inf")):
                raise ValueError(f"feature '{name}' is not finite")
            if abs(value) > 1e6:
                raise ValueError(f"feature '{name}' is out of range")
        return v

    @field_validator("prediction_type")
    @classmethod
    def validate_prediction_type(cls, v: str) -> str:
        allowed = {
            "malaria_risk",
            "asthma_exacerbation",
            "typhoid_risk",
        }
        if v not in allowed:
            raise ValueError("unknown prediction type")
        return v


class PredictionResponse(BaseModel):
    """Decision-support output. Explicitly NOT a medical diagnosis."""

    success: Literal[True] = True
    prediction_type: str
    risk_level: Literal["low", "moderate", "high"]
    risk_score: float
    confidence: float
    model_version: str
    served_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    disclaimer: str = (
        "This output is generated by a decision-support model. It is "
        "informational only and is not a medical diagnosis. A qualified "
        "healthcare professional must make all clinical decisions."
    )


class ModelInfo(BaseModel):
    prediction_type: str
    version: str
    path: str
    sha256: str | None = None
    available: bool


class ModelsListResponse(BaseModel):
    success: Literal[True] = True
    models: list[ModelInfo]


class SymptomAssessRequest(BaseModel):
    """Symptom assessment input entered by healthcare staff.

    ``symptoms_text`` is the free-text description of the symptoms the student
    reported. ``student_ref`` is the same opaque, non-PII identifier used by
    the prediction endpoint.
    """

    symptoms_text: Annotated[str, Field(min_length=1, max_length=MAX_SYMPTOM_TEXT_LEN)]
    student_ref: Annotated[str, Field(max_length=MAX_STUDENT_REF_LEN)] = ""

    @field_validator("symptoms_text")
    @classmethod
    def validate_symptoms_text(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("symptoms_text must not be blank")
        return v


class SymptomCondition(BaseModel):
    """One ranked suggestion. Explicitly not a diagnosis."""

    condition: Annotated[str, Field(min_length=1, max_length=120)]
    level: Literal["low", "moderate", "high"]
    score: float
    confidence: float
    advice: Annotated[str, Field(max_length=1000)]


class SymptomAssessResponse(BaseModel):
    """Decision-support output for the symptom assessment."""

    success: Literal[True] = True
    conditions: list[SymptomCondition]
    matched_symptoms: list[str]
    model_version: str
    served_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    disclaimer: str = (
        "This suggestion is generated by a decision-support assistant from the "
        "symptoms entered by healthcare staff. It is informational only and is "
        "not a medical diagnosis. A qualified healthcare professional must "
        "confirm any condition and decide on treatment."
    )


class HealthResponse(BaseModel):
    status: Literal["ok"]
    service: str
    version: str
    auth_enabled: bool
    uptime_seconds: int
    model_registry: list[dict]